# Generated by Django 3.2.7 on 2021-10-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('greeting', models.TextField()),
            ],
        ),
    ]
